# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "lazygit-unstable-${version}";
  version = "2018-08-06";
  rev = "6126ddd373ddf18b96566eb1ddc204f017b449cb";

  goPackagePath = "github.com/jesseduffield/lazygit";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/jesseduffield/lazygit";
    sha256 = "1a9bf01qvxgrnknghabbjxv547i6x2hqydrp4dqh4jbf4gv4wg4j";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
