# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/fatih/color";
    fetch = {
      type = "git";
      url = "https://github.com/fatih/color";
      rev = "2d684516a8861da43017284349b7e303e809ac21";
      sha256 = "1fcfmz4wji3gqmmsdx493r7d101s58hwjalqps6hy25nva5pvmfs";
    };
  }
  {
    goPackagePath = "github.com/golang-collections/collections";
    fetch = {
      type = "git";
      url = "https://github.com/golang-collections/collections";
      rev = "604e922904d35e97f98a774db7881f049cd8d970";
      sha256 = "04g0xc1bs4aphc2rcj9knah2shmck500qagnazy4mg052b84ggwm";
    };
  }
  {
    goPackagePath = "github.com/jesseduffield/gocui";
    fetch = {
      type = "git";
      url = "https://github.com/jesseduffield/gocui";
      rev = "3c923f53ac9952af649af04a067405843558d56f";
      sha256 = "1ybgwbbrii3iv49sjjr98fzxf8ypj355d08rp10lk8afll871zql";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-runewidth";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-runewidth";
      rev = "ce7b0b5c7b45a81508558cd1dba6bb1e4ddb51bb";
      sha256 = "0lc39b6xrxv7h3v3y1kgz49cgi5qxwlygs715aam6ba35m48yi7g";
    };
  }
  {
    goPackagePath = "github.com/nsf/termbox-go";
    fetch = {
      type = "git";
      url = "https://github.com/nsf/termbox-go";
      rev = "5c94acc5e6eb520f1bcd183974e01171cc4c23b3";
      sha256 = "1fi8imdgwvlsgifw2qfl3ww0lsrgkfsimkzz7bnrq41nar78s0fw";
    };
  }
]
