# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn, libpcap }:

buildGoPackage rec {
  name = "netcap-unstable-${version}";
  version = "2018-12-22";
  rev = "adcc19cd58065cb3610d54f3cd26b2243c3f3ec8";

  goPackagePath = "github.com/dreadl0ck/netcap";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/dreadl0ck/netcap";
    sha256 = "0z92inra65yay5s03x84pyh12a8q67wlp75l5najihi3p0lwm1n5";
  };

  goDeps = ./deps.nix;

  buildInputs = [ libpcap ];

  preInstall = ''
    mv ./go/bin/cmd ./go/bin/netcap
    mv ./go/bin/sensor ./go/bin/netcap-sensor
    mv ./go/bin/server ./go/bin/netcap-server
  '';
}
