# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/dreadl0ck/ja3";
    fetch = {
      type = "git";
      url = "https://github.com/dreadl0ck/ja3";
      rev = "e26c0a21084f7160ec2d15516b9339659e9c4557";
      sha256 = "0jrcfxvyzs0avw3768wr9qszl2jjdswsbd7mw7b3p7llxnzm5890";
    };
  }
  {
    goPackagePath = "github.com/dreadl0ck/tlsx";
    fetch = {
      type = "git";
      url = "https://github.com/dreadl0ck/tlsx";
      rev = "5334a78b2ee24a7f444180c9a2f12b98744a3f0a";
      sha256 = "058ljbdh6v0afh7cbnqw8f9y28301aczd046cid0phnc33kcclmm";
    };
  }
  {
    goPackagePath = "github.com/dustin/go-humanize";
    fetch = {
      type = "git";
      url = "https://github.com/dustin/go-humanize";
      rev = "9f541cc9db5d55bce703bd99987c9d5cb8eea45e";
      sha256 = "1kqf1kavdyvjk7f8kx62pnm7fbypn9z1vbf8v2qdh3y7z7a0cbl3";
    };
  }
  {
    goPackagePath = "github.com/evilsocket/islazy";
    fetch = {
      type = "git";
      url = "https://github.com/evilsocket/islazy";
      rev = "383e73d128d816f7e12ff68b01154a2da51217ac";
      sha256 = "0bgmd4kkf50jz7ac5cyy8hm87lrj076y1anda7ph8awn1x9j6wdv";
    };
  }
  {
    goPackagePath = "github.com/gogo/protobuf";
    fetch = {
      type = "git";
      url = "https://github.com/gogo/protobuf";
      rev = "4cbf7e384e768b4e01799441fdf2a706a5635ae7";
      sha256 = "1c3y5m08mvrgvlw0kb9pldh3kkqcj99pa8gqmk1g3hp8ih3b2dv0";
    };
  }
  {
    goPackagePath = "github.com/golang/protobuf";
    fetch = {
      type = "git";
      url = "https://github.com/golang/protobuf";
      rev = "1d3f30b51784bec5aad268e59fd3c2fc1c2fe73f";
      sha256 = "1wx76776z48qd9pjnrydhj1f3k94qlbcj32ak6am7n7w2nda7sjx";
    };
  }
  {
    goPackagePath = "github.com/google/gopacket";
    fetch = {
      type = "git";
      url = "https://github.com/google/gopacket";
      rev = "aae514bb9b6e0b934378e3eb1381a7783821fc16";
      sha256 = "0wwzfx9dphvlq9gcxgvqq8h2m1cg8j9k62bki70wxzznr007f31d";
    };
  }
  {
    goPackagePath = "github.com/google/kythe";
    fetch = {
      type = "git";
      url = "https://github.com/google/kythe";
      rev = "f1ef34b5e227e4807ae65173ff0e1e325971fe9e";
      sha256 = "1845iaqn60bpqbivawchpc7r3y5zg6n7g06ik2qkvafg57jlcqvj";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-colorable";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-colorable";
      rev = "efa589957cd060542a26d2dd7832fd6a6c6c3ade";
      sha256 = "0kshi4hvm0ayrsxqxy0599iv81kryhd2fn9lwjyczpj593cq069r";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-isatty";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-isatty";
      rev = "3fb116b820352b7f0c281308a4d6250c22d94e27";
      sha256 = "084hplr4n4g5nvp70clljk428hc963460xz0ggcj3xdi4w7hhsvv";
    };
  }
  {
    goPackagePath = "github.com/mdlayher/raw";
    fetch = {
      type = "git";
      url = "https://github.com/mdlayher/raw";
      rev = "fa5ef3332ca961deab5782da07b1616fea8a9dd8";
      sha256 = "1vjxcfjcw6kcm4a2f0s8han2palfxww34wgw116kmcc4sd1m3frh";
    };
  }
  {
    goPackagePath = "github.com/mgutz/ansi";
    fetch = {
      type = "git";
      url = "https://github.com/mgutz/ansi";
      rev = "9520e82c474b0a04dd04f8a40959027271bab992";
      sha256 = "00bz22314j26736w1f0q4jy9d9dfaml17vn890n5zqy3cmvmww1j";
    };
  }
  {
    goPackagePath = "github.com/sirupsen/logrus";
    fetch = {
      type = "git";
      url = "https://github.com/sirupsen/logrus";
      rev = "2067ea4241cec716fbd0ac90f42f339f963bff92";
      sha256 = "1vbvvv2zwkx94vaqam9l429jcsprd7wrbzzgl98m5p1xd9phi896";
    };
  }
  {
    goPackagePath = "github.com/x-cray/logrus-prefixed-formatter";
    fetch = {
      type = "git";
      url = "https://github.com/x-cray/logrus-prefixed-formatter";
      rev = "bb2702d423886830dee131692131d35648c382e2";
      sha256 = "0mqcdiix0bw0hj6yksiyn4rmgnzblj3x4wdzvf03y0d9vg1zr1na";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "505ab145d0a99da450461ae2c1a9f6cd10d1f447";
      sha256 = "1vbsvcvmjz6c00p5vf8ls533p52fx2y3gy6v4k5qrdlzl4wf0i5s";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "927f97764cc334a6575f4b7a1584a147864d5723";
      sha256 = "0np7b766gb92vbm514yhdl7cjmqvn0dxdxskd84aas2ri1fkpgw5";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "b4a75ba826a64a70990f11a225237acd6ef35c9f";
      sha256 = "0kzrd2wywkcq35iakbzplqyma4bvf2ng3mzi7917kxcbdq3fflrj";
    };
  }
  {
    goPackagePath = "kythe.io";
    fetch = {
      type = "git";
      url = "https://github.com/kythe/kythe";
      rev = "f1ef34b5e227e4807ae65173ff0e1e325971fe9e";
      sha256 = "1845iaqn60bpqbivawchpc7r3y5zg6n7g06ik2qkvafg57jlcqvj";
    };
  }
  {
    goPackagePath = "github.com/dreadl0ck/cryptoutils";
    fetch = {
      type = "git";
      url = "https://github.com/dreadl0ck/cryptoutils";
      rev = "7a8d1abd4ff19604cb77bdfb2d3f92ec35bb1156";
      sha256 = "0idys45r2phpvvyfns1kd8cks0xh77dj8nsb27hfmi6i1phqgxrp";
    };
  }
  {
    goPackagePath = "gopkg.in/cheggaaa/pb.v1";
    fetch = {
      type = "git";
      url = "https://github.com/cheggaaa/pb";
      rev = "1cc5bbe20449079337944d56292c7383510c534c";
      sha256 = "1f995nsqgi0r4qc16nmxlbdxc536hkfwa5k9xb8ypz8d6jlkihag";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-runewidth";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-runewidth";
      rev = "703b5e6b11ae25aeb2af9ebb5d5fdf8fa2575211";
      sha256 = "0znpyz71gajx3g0j2zp63nhjj2c07g16885vxv4ykwnrfmzbgk4w";
    };
  }
]
